create table prova.dim_participante(
DP_NU_INSCRICAO               NUMBER NOT NULL,
DP_NU_ANO                     NUMBER NULL,
DP_TP_FAIXA_ETARIA            VARCHAR(20) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_TP_SEXO                    VARCHAR(10) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_TP_ESTADO_CIVIL            VARCHAR(40) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_TP_COR_RACA                VARCHAR(20) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_TP_NACIONALIDADE           VARCHAR(50) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_TP_ST_CONCLUSAO            VARCHAR(60) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_TP_ANO_CONCLUIU            VARCHAR(20) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_TP_ESCOLA                  VARCHAR(20) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_TP_ENSINO                  VARCHAR(50) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_IN_TREINEIRO               VARCHAR(10) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_TP_LINGUA                  VARCHAR(10) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q001                       VARCHAR(100) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q002                       VARCHAR(100) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q003                       VARCHAR(10) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q004                       VARCHAR(10) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q005                       NUMBER NULL,
DP_Q006                       VARCHAR(40) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q007                       VARCHAR(40) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q008                       VARCHAR(30) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q009                       VARCHAR(30) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q010                       VARCHAR(30) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q011                       VARCHAR(30) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q012                       VARCHAR(30) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q013                       VARCHAR(30) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q014                       VARCHAR(30) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q015                       VARCHAR(30) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q016                       VARCHAR(30) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q017                       VARCHAR(30) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q018                       VARCHAR(30) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q019                       VARCHAR(30) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q020                       VARCHAR(30) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q021                       VARCHAR(30) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q022                       VARCHAR(30) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q023                       VARCHAR(30) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q024                       VARCHAR(30) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DP_Q025                       VARCHAR(30) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
CONSTRAINT PK_DP_NU_INSCRICAO PRIMARY KEY(DP_NU_INSCRICAO)
) ENGINE = innodb;


create table prova.dim_escola(
DE_CO_MUNICIPIO_ESC           NUMBER NOT NULL,
DE_NO_MUNICIPIO_ESC           VARCHAR(150) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DE_CO_UF_ESC                  NUMBER NULL,
DE_SG_UF_ESC                  VARCHAR(2) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DE_TP_DEPENDENCIA_ADM_ESC     VARCHAR(20) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci',
DE_TP_LOCALIZACAO_ESC         VARCHAR(10) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci',
DE_TP_SIT_FUNC_ESC            VARCHAR(40) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci',
CONSTRAINT PK_DE_CO_MUNICIPIO_ESC PRIMARY KEY(DE_CO_MUNICIPIO_ESC,DE_TP_DEPENDENCIA_ADM_ESC,DE_TP_LOCALIZACAO_ESC,DE_TP_SIT_FUNC_ESC)
) ENGINE = innodb;


create table prova.dim_local_prova(
DLP_CO_MUNICIPIO_PROVA         NUMBER NOT NULL,
DLP_NO_MUNICIPIO_PROVA         VARCHAR(150) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DLP_CO_UF_PROVA                VARCHAR(2) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
DLP_SG_UF_PROVA                VARCHAR(2) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
CONSTRAINT PK_DLP_CO_MUNICIPIO_PROVA PRIMARY KEY(DLP_CO_MUNICIPIO_PROVA)
) ENGINE = innodb;


create table prova.fato_prova(
FP_NU_INSCRICAO               NUMBER NOT NULL,
FP_CO_MUNICIPIO_ESC           NUMBER NULL,
FP_TP_DEPENDENCIA_ADM_ESC     VARCHAR(20) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
FP_TP_LOCALIZACAO_ESC         VARCHAR(10) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
FP_TP_SIT_FUNC_ESC            VARCHAR(40) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
FP_CO_MUNICIPIO_PROVA         NUMBER NULL,
FP_TP_PRESENCA_CN             VARCHAR(20) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
FP_TP_PRESENCA_CH             VARCHAR(20) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
FP_TP_PRESENCA_LC             VARCHAR(20) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
FP_TP_PRESENCA_MT             VARCHAR(20) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
FP_CO_PROVA_CN                VARCHAR(40) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
FP_CO_PROVA_CH                VARCHAR(40) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
FP_CO_PROVA_LC                VARCHAR(40) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
FP_CO_PROVA_MT                VARCHAR(40) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
FP_NU_NOTA_CN                 DECIMAL(10,1) NULL,
FP_NU_NOTA_CH                 DECIMAL(10,1) NULL,
FP_NU_NOTA_LC                 DECIMAL(10,1) NULL,
FP_NU_NOTA_MT                 DECIMAL(10,1) NULL,
FP_TX_RESPOSTAS_CN            VARCHAR(45) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
FP_TX_RESPOSTAS_CH            VARCHAR(45) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
FP_TX_RESPOSTAS_LC            VARCHAR(50) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
FP_TX_RESPOSTAS_MT            VARCHAR(45) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
FP_TX_GABARITO_CN             VARCHAR(45) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
FP_TX_GABARITO_CH             VARCHAR(45) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
FP_TX_GABARITO_LC             VARCHAR(50) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
FP_TX_GABARITO_MT             VARCHAR(45) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
FP_TP_STATUS_REDACAO          VARCHAR(40) CHARACTER SET 'UTF8' COLLATE 'utf8_general_ci' NULL,
FP_NU_NOTA_COMP1              NUMBER NULL,
FP_NU_NOTA_COMP2              NUMBER NULL,
FP_NU_NOTA_COMP3              NUMBER NULL,
FP_NU_NOTA_COMP4              NUMBER NULL,
FP_NU_NOTA_COMP5              NUMBER NULL,
FP_NU_NOTA_REDACAO            NUMBER NULL,
CONSTRAINT PK_FP_NU_INSCRICAO PRIMARY KEY(FP_NU_INSCRICAO)
) ENGINE = innodb;


ALTER TABLE prova.fato_prova ADD CONSTRAINT FK_FP_DP FOREIGN KEY (FP_NU_INSCRICAO) REFERENCES prova.dim_participante (DP_NU_INSCRICAO);

ALTER TABLE prova.fato_prova ADD CONSTRAINT FK_FP_DE FOREIGN KEY (FP_CO_MUNICIPIO_ESC,FP_TP_DEPENDENCIA_ADM_ESC,FP_TP_LOCALIZACAO_ESC,FP_TP_SIT_FUNC_ESC)
REFERENCES prova.dim_escola (DE_CO_MUNICIPIO_ESC,DE_TP_DEPENDENCIA_ADM_ESC,DE_TP_LOCALIZACAO_ESC,DE_TP_SIT_FUNC_ESC) ;

ALTER TABLE prova.fato_prova ADD CONSTRAINT FK_FP_DLP FOREIGN KEY (FP_CO_MUNICIPIO_PROVA) REFERENCES prova.dim_local_prova (DLP_CO_MUNICIPIO_PROVA) ;